name: Build, Lint, and Deploy

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript and React
        run: npm run build

      - name: Run ESLint
        run: npm run lint
